version: '3'
services:
  clickhouse-server:
    image: echo009/clickhouse-server:20.6.7.4-aarch64
    restart: always
    container_name: clickhouse-server
    privileged: true
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    volumes:
      - ./data:/var/lib/clickhouse
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./config.xml:/etc/clickhouse-server/config.xml
