cluster.name: "es-cluster"
node.name: "es-node-1"
network.host: 0.0.0.0
http.port: 9200
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "Authorization,X-Requested-With,Content-Length,Content-Type"
node.master: true
reindex.remote.whitelist: ['other:9200']

xpack.security.enabled: false
xpack.security.authc.api_key.enabled: false
cluster.routing.allocation.disk.watermark.flood_stage: 99%