version: '3'
services:
  postgres:
    image: postgres:12.6
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: Echo009
      POSTGRES_PASSWORD: ironman
      POSTGRES_DB: alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf