version: '3'
services:
  mongodb:
    image: mongo:4.2
    restart: always
    container_name: mongodb
    command:
      --config /etc/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: alpine
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./log/mongod.log:/var/log/mongodb/mongod.log
      - ./mongod.conf:/etc/mongod.conf
