version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.18
    container_name: elastic_search
    restart: always
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx4g"
      - "discovery.type=single-node"
      - "COMPOSE_PROJECT_NAME=elasticsearch-server"

