version: '3'
services:
  redis:
    image: redis:6.2.1-alpine
    restart: always
    container_name: redis
    command: redis-server /etc/redis.conf
    ports:
      - 6379:6379
    privileged: true
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis.conf